name: Trigger auto deployment for azuremongo

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/azuremongo-AutoDeployTrigger-ea9fbb9a-5daa-4bac-abd2-f78fca877390.yml'

  # Allow mannually trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZUREMONGO_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: azuresampleproject.azurecr.io
          registryUsername: ${{ secrets.AZUREMONGO_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.AZUREMONGO_REGISTRY_PASSWORD }}
          containerAppName: azuremongo
          resourceGroup: DefaultResourceGroup-EUS
          imageToBuild: azuresampleproject.azurecr.io/azuremongo:latest
          runtimeArgs: '--runtime-platform docker'
          

     

